Welcome
=======

The _What is Cancer Like_ project grew out of my experience with Lymphoma. I remember during the time between diagnosis and the beginning of chemo, then during chemo, and when the treatment was done and the next phase began, I had a lot of uncertainty about what was going to happen. What was it going to be like? It would have been great if there was a site with people talking about what was coming up for me.

So here it is, my attempt to build that site. I am doing it as part of my work at Red Hat, where, as a Developer Evangelist for OpenShift I build an application once a quarter. 

Here is the general outline of the application

1) Main page with some recent videos
2) Main Page search that allows you to find based on condition and treatments
3) Not sure if I should allow people to connect together on my site - might be nicer than the video site
4) Log in to add video through Google and Vimeo 
5) Comments managed through disqus or some other system

Infrastructure
1) Django
2) Postgresql
3) HTML5 Boilerplate
4) Disqus for comments or something similar
5) Angular?
